/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package vdjserver;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Nucleotide_defined implements org.apache.thrift.TEnum {
  Nucleotide_defined_A(0),
  Nucleotide_defined_C(1),
  Nucleotide_defined_G(2),
  Nucleotide_defined_T(3),
  Nucleotide_defined_U(4),
  Nucleotide_defined_a(5),
  Nucleotide_defined_c(6),
  Nucleotide_defined_g(7),
  Nucleotide_defined_t(8),
  Nucleotide_defined_u(9);

  private final int value;

  private Nucleotide_defined(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Nucleotide_defined findByValue(int value) { 
    switch (value) {
      case 0:
        return Nucleotide_defined_A;
      case 1:
        return Nucleotide_defined_C;
      case 2:
        return Nucleotide_defined_G;
      case 3:
        return Nucleotide_defined_T;
      case 4:
        return Nucleotide_defined_U;
      case 5:
        return Nucleotide_defined_a;
      case 6:
        return Nucleotide_defined_c;
      case 7:
        return Nucleotide_defined_g;
      case 8:
        return Nucleotide_defined_t;
      case 9:
        return Nucleotide_defined_u;
      default:
        return null;
    }
  }
}
