/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package vdjserver;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Segment_type implements org.apache.thrift.TEnum {
  Segment_type_D(0),
  Segment_type_J(1),
  Segment_type_V(2);

  private final int value;

  private Segment_type(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Segment_type findByValue(int value) { 
    switch (value) {
      case 0:
        return Segment_type_D;
      case 1:
        return Segment_type_J;
      case 2:
        return Segment_type_V;
      default:
        return null;
    }
  }
}
