/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "airr_constants.h"

namespace airr {

const airrConstants g_airr_constants;

airrConstants::airrConstants() {
}

} // namespace

